services:

  postgres:
    image: postgres:16
    container_name: hireiq_postgres
    restart: always

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: django_app/Dockerfile

    container_name: hireiq_django

    restart: always

    depends_on:
      - postgres
      - ml_api

    env_file:
      - .env

    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      ML_API_URL: ${ML_API_URL}

    expose:
      - "8000"

    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media

  ml_api:
    build:
      context: .
      dockerfile: ml_api/Dockerfile

    container_name: hireiq_ml_api

    restart: always

    env_file:
      - .env

    expose:
      - "8001"

    volumes:
      - chroma_data:/app/chroma_db

  nginx:
    image: nginx:latest

    container_name: hireiq_nginx

    restart: always

    depends_on:
      - django
      - ml_api

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/app/staticfiles:ro
      - media_data:/app/media:ro

volumes:
  postgres_data:
  chroma_data:
  static_data:
  media_data: