# Generated by Django 5.2.14 on 2026-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
